### ISSUE TITLE
Two different versions of EW: support the mod together?

### ISSUE THREAD

**Issue by JulyMorning** [Adventurer13/ExpandedWoodworking#20]
I'm an old school RimWorld gamer, just came back to the community after a 2-year long pause. Noticed that there're supporters of the good old mod (the second is [here](https://github.com/indented-automation/ExtendedWoodworking)). Don't know what are the differences between your versions, but I'm already aware that compatibility with other mods differs. Maybe you should maintain the mod together?

**Comment by Adventurer13** [comment]
Ah, there are some differences between Extended Woodworking (which you linked to) and Expanded Woodworking. While they both originate (and have the same acronym, confusingly) from A13 Extended Woodworking by ItchyFlea, Expanded Woodworking is more of a fork (originally created by Qwynn) from the original by expanding its scope and features. 

Extended Woodworking has kept very similar to the original with smaller scope of trees dropping different wood logs and you being able to "paint" different colors by changing to the color of the logs.

Expanded Woodworking has taken the primary component of different logs for different trees and expanded upon this through adding lumber as a new building material. It has taken a bit more realistic of an approach requiring lumber for some items and logs for others and does not include painting. Also, if using the Vegetable Garden Project (VGP) mods and the associated VGP patch for Expanded Woodworking, you'll get wood when harvesting fruit trees to give them more of a benefit. This is also included with the Cocoa tree in vanilla Rmworld. 

They have similarities, but Expanded Woodworking forked from the original scope of the mod. Some may prefer the smaller scope and less materials added by Extended Woodworking, so these each remain as separate mods. They are both good mods on adding wood/color variety to to vanilla Rimworld.
