### ISSUE TITLE
Generators, stoves, and passive coolers not working

### ISSUE THREAD

**Issue by Batarn** [Adventurer13/ExpandedWoodworking#26]
Hello! I want to say I'm a big fan of your mods, but I believe I have encountered issues. Everytime I use expanded wood working, I cannot refill the Wood fuel generators, stoves that use wood, or the passive coolers. I turned the mod off and I was able to use those items again, but when I turned it back on, the issue persisted.

https://drive.google.com/file/d/1IO_uVCUU6m7_hvMh_zrMwchUOepXCkWj/view?usp=sharing

https://drive.google.com/file/d/1lIXWjpdfkV8yDPZfW0H4ki3fkCObtCop/view?usp=sharing

https://drive.google.com/file/d/1ETXQJh6_6sHjJCvgnMBCKwSTu6Xkv8gN/view?usp=sharing

**Comment by Adventurer13** [comment]
Transferring to EW repository since fuel patching is done within that mod.

Passive coolers don't have refueling in vanilla and I don't add it. Your other problems are likely a load order issue with another mod overwriting the fuel patching EW does. What's your load order?

**Comment by Adventurer13** [comment]
Just an update since I have more time now then before to work on this. I cannot recreate your problem. All of those machines refuel perfectly fine on my end. I cannot access the first two files you posted links to. For the third, I am going to need actual mod names, not steam workshop file numbers.
