### ISSUE TITLE
Trees Drop Mixed Lumber?

### ISSUE THREAD

**Issue by BlueTressym** [Adventurer13/ExpandedWoodworking#4]
Hiya.  Following up on my testing for the trader issue, I tested with just this mod and 'Fertile Planet' in that order and the trees dropped 'mixed lumber' instead of logs.  Switching them round, so 'Fertile Planet' was BEFORE this mod seemed to 'fix' it, as in the trees then dropped the appropriate logs.  

I'm a little concerned as I know that on the Steam page it states that mods like FP or 'Increased Forest Density' should be loaded AFTER this.  Am I missing something obvious here?  

*confuzzled kitty*

PS:  I realised somewhat belatedly that I probably should have posted the trader issue here too.  I apologise.

**Comment by Adventurer13** [comment]
I'll have to look into it. I forgot how Fertile Planet edits the trees. Sometimes different mods edit these things differently. 

Sorry for taking this long to respond.
