### ISSUE TITLE
ReGrowth - Cold Bog

### ISSUE THREAD

**Issue by KennethSamael** [Adventurer13/ExpandedWoodworking#41]
This mod got updated recently, adding a new tree, called "Karim tree". Apparently it's inspired by some tree he found in Skyrim, which isn't very helpful, but I guess it means that it's at least indirectly inspired by a real life tree. So we got a tall, bushy, deciduous tree that grows in cold, wet climates. I only did some basic googling and mostly looked for pictures I could convince myself looked similar enough, and I feel some kind of ash tree might fit the bill. Or maybe oak. Might also be worth checking with the guy in the comments to see what he came up with, looks like he's been making his own set of patches independently.

Also, the other tree got renamed to RG-CBE_Plant_SpruceTreePine, so the patch for that has to be changed.

**Comment by Adventurer13** [comment]
I've added support for the Karim tree and fixed the name of the other within the patch. Ended up going with [black ash](https://www.wood-database.com/black-ash/).
